// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
        classpath "org.jacoco:org.jacoco.core:0.8.8"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply plugin: 'jacoco'

jacoco {
    toolVersion = "0.8.8"
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    doLast {
        rootProject.buildDir.deleteDir()
        project(':NdkBinderService').buildDir.deleteDir()
        project(':JavaBinderClient').buildDir.deleteDir()
        project(':JavaBinderService').buildDir.deleteDir()
        project(':NdkBinderClient').buildDir.deleteDir()
    }
}

task jacocoTestReport(type: JacocoReport, group: 'verification') {
    dependsOn ':Common:testDebugUnitTest',
            ':NdkBinderService:testDebugUnitTest',
            ':NdkBinderClient:testDebugUnitTest',
            ':JavaBinderService:testDebugUnitTest',
            ':JavaBinderClient:testDebugUnitTest'

    reports {
        xml.required = true
        html.required = true
    }

    def fileFilter = [
            '**/R.class',
            '**/R$*.class',
            '**/BuildConfig.*',
            '**/Manifest*.*',
            '**/*Test*.*',
            'android/**/*.*',
            '**/*$ViewInjector*.*',
            '**/*$ViewBinder*.*',
            '**/Lambda$*.class',
            '**/Lambda.class',
            '**/*Lambda.class',
            '**/*Lambda*.class'
    ]

    def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.setFrom(files([mainSrc]))
    classDirectories.setFrom(files([debugTree]))
    executionData.setFrom(fileTree(dir: project.buildDir, includes: [
            'jacoco/testDebugUnitTest.exec',
            'outputs/code_coverage/debugAndroidTest/connected/*coverage.ec'
    ]))
}
